## Блок 2

### Шаг 2

In [3]:
import pandas as pd
ratings = pd.read_csv('ratings.csv')


# Посчитаем количество уникальных значений user_id и минимальный рейтинг
print(len(ratings['userId'].unique()))
print(ratings['rating'].min())

671
0.5

### Шаг 3

In [5]:
# Посчитаем, какое максимальное количество оченок выставлено одним пользователем
# (соответсвует чилу строк, относящихся к одному userId)
ratings.groupby('userId').count().max()

movieId      2391
rating       2391
timestamp    2391
dtype: int64

### Шаг 4

In [6]:
ratings_count = ratings.groupby('userId').count().reset_index()[['userId', 'movieId']]

# Получим список пяти первых пользователей, поставивших не менее 50 оценок
film_fans_ratings_count = ratings_count[ ratings_count['movieId'] >= 50 ]
film_fans_user_ids = film_fans_ratings_count['userId'].tolist()
film_fans_user_ids[:5]

[2, 3, 4, 5, 7]

### Шаг 6

In [15]:
# Получаем новый датафрейм
film_fans_ratings_count = ratings_count[ ratings_count['movieId'] >= 100 ]
film_fans_user_ids = film_fans_ratings_count['userId'].tolist()
fans_data = ratings[ ratings['userId'].isin(film_fans_user_ids) ]
# Группируем по userId и получаем минимальное и максимальное значения timestamp
min_max_df = fans_data.groupby('userId').agg(['min', 'max'])
# Считаем новый столбец diff
min_max_df['diff'] = min_max_df['timestamp']['max'] - min_max_df['timestamp']['min']
# Получаем ответ в секундах
min_max_df['diff'].mean() / 3600 / 24

455.2285713719898

## Блок 3

### Шаг 1, 2 и 3

In [16]:
data = pd.read_csv('ratings.csv')
data[ data['userId'] == 1 ]['rating'].value_counts()
data.pivot_table(index = 'userId', columns = 'rating', values = 'timestamp', aggfunc = 'count')
data_pivot = data.pivot_table(index = 'userId', columns = 'rating', values = 'timestamp', aggfunc = 'count', fill_value = 0)
data_pivot = data.pivot_table(index = 'userId', columns = 'rating', values = 'timestamp', aggfunc = 'count', fill_value = 0, margins=True)
data_pivot.head()

rating  0.5  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  All
userId
1         0    2    0    7    3    4    1    3    0    0   20
2         0    2    0    4    0   36    0   23    0   11   76
3         0    0    0    1    3   18    9   11    4    5   51
4         0    5    0    5    0   23    0   52    0  119  204
5         0    0    1    0    3    3   27   42   19    5  100

### Шаг 4

In [23]:
# Найдем, какое максимальное количество пятерок поставил один пользователей
data_pivot.sort_values(5.0, ascending=False) # 408 - искомый ответ

rating   0.5   1.0   1.5   2.0   2.5    3.0    3.5    4.0   4.5    5.0     All
userId
All     1101  3326  1687  7271  4449  20064  10538  28750  7723  15095  100004
564        0   152     0   187     0    414      0    707     0    408    1868
232        0    35     0    32     0     96      0    276     0    243     682
242        0     0     0     4     0     25      0    151     0    219     399
547       53    79    58   204   177    411    378    591   226    214    2391
30         0    20     0    86     0    201      2    505     1    196    1011
472        0    23     1    56     5    188     13    315    40    189     830
102        0     8     0    40     0     87      0    369     0    174     678
358        0   114     0    91     0    118      0    156     0    138     617
388        0    27     1    78    10    165     35    297    44    135     792
481        0     4     2    10    11     29     55    118    74    133     436
518        0    25     0    55     0    249      0    246     0    132     707
287        2     0     0     0     1      5     14     45    63    124     254
128        0    16     0    29     0     60      0     97     0    121     323
585        0     1     0     4     0     34      0    141     0    120     300
4          0     5     0     5     0     23      0     52     0    119     204
537        0     9     0    20     0     52      0    108     0    118     307
387        0     3     0     5     0     36      0    121     0    114     279
577        1     2     3     2     4      8     26     54    69    110     279
558        0     1     0     2     0     27      0     78     0    107     215
78         0     1     3     4     6      8     32     53    52    104     263
407        0     1     0     7     0     48      5    128    32    102     323
119        0    16     0   106     0    161      0    257     0    101     641
56         0    14     0   126     0      0      0    289     0     93     522
15        83   274   128   217   141    312    146    251    56     92    1700
575        0    22     0    84     0    186      0    166     0     89     547
431        4     2     0     8     5     32      8     61    60     88     268
452       14    80    22   147    49    415    120    379    28     86    1340
656        0     2     0     2     0      6      0     35     0     83     128
57         0     9     0    14     0     37      0     66     0     83     209
...      ...   ...   ...   ...   ...    ...    ...    ...   ...    ...     ...
35         2     1     5     2     3      1      2      3     0      1      20
604        0     3     2     3     1      2      3      4     1      1      20
76         0     0     0     1     0      2      6      6     4      1      20
77         8     5     8    19    30     49     72     91    33      0     315
263        0     2     1     6     6     38     38     20     3      0     114
79         5     0     0     7    19     20      3      1     0      0      55
579       14     0     0     2     1      1      2      0     1      0      21
485        0     1     0     0     3      3      4      5     4      0      20
429        2     1     3     8     6      5      0      2     0      0      27
424        1     3     0     2     0      3     11      5     5      0      30
419        0     0     0     1     4      8     17      7    13      0      50
397        0     0     1     1     6     12     15     16     8      0      59
392        0     2     2     4     0      5      2      8     2      0      25
378       21     1     0     1     5     20     36     39    24      0     147
353       15    41    42    73    81    125    121     20     3      0     521
557        5     3     3    12     9      9     12     11     2      0      66
325        0     2     4     5     1      2      2      2     2      0      20
276        1     1     2     2     1      6      2      5     1      0      21
638        1     2     1     2     1      2      5      2     4      0      20
591        0     0     2     2     4      5      9      5     3      0      30
226        1     0     4     3     2      6      6     12     2      0      36
221        0     1     0     2     5      9      2      1     0      0      20
210        0     0     0     1    16      6      5      2     2      0      32
209        0     1     0     5     0     10      0      4     0      0      20
174        1     1     1     2     2      3      4      4     3      0      21
170        0     2     2     5     5      9      1      1     1      0      26
158        0     0     3     2     2      1      5      7     1      0      21
157        3     6     6    14    30     59     78     92    38      0     326
633        0     0     0     3     0     22      0      7     0      0      32
1          0     2     0     7     3      4      1      3     0      0      20

[672 rows x 11 columns]

## Блок 4

### Шаги 1, 2, 3

In [24]:
# Выполняем предварительные действия, описанные в модуле
import pandas as pd
data = pd.read_csv('ratings.csv')
data_pivot = data.pivot_table(index = ['movieId', 'rating'], values = 'timestamp', aggfunc = 'count').reset_index()
data_pivot['sum'] = data_pivot.groupby('movieId').timestamp.transform(lambda x: sum(x))

### Шаг 4

In [26]:
# Найдем сумму столбца share для movieId = 1
data_pivot['share'] = data_pivot['timestamp'] / data_pivot['sum']
print(data_pivot[data_pivot['movieId'] == 1]['share'].sum())

1.0

## Блок 5

In [39]:
# Создадим новый стобец в датафрейме, как этого требует задание:
import pandas as pd
data_pivot['class'] = data_pivot['rating'].apply(lambda x: 'Низкий' if x <= 2 else ('Высокий' if x > 4 else 'Средний'))
# Ответим на поставленный вопрос
print(data_pivot[(data_pivot['movieId'] == 356) & (data_pivot['class'] == 'Средний')]['share'].sum())

0.551319648094